# Generated by Django 5.2.7 on 2025-10-18 03:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='名')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='姓')),
                ('first_name_kana', models.CharField(blank=True, max_length=30, verbose_name='名（カナ）')),
                ('last_name_kana', models.CharField(blank=True, max_length=30, verbose_name='姓（カナ）')),
                ('role', models.CharField(choices=[('candidate', '候補者'), ('recruiter', '採用担当者'), ('interviewer', '面接官'), ('admin', '管理者')], default='candidate', max_length=20, verbose_name='役割')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='アバター')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('is_staff', models.BooleanField(default=False, verbose_name='スタッフ')),
                ('is_verified', models.BooleanField(default=False, verbose_name='メール認証済み')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最終ログイン')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('cognito_user_id', models.CharField(blank=True, max_length=100, verbose_name='Cognito User ID')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
                'db_table': 'users',
            },
        ),
    ]
