# Generated by Django 5.2.7 on 2025-10-18 03:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiasReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bias_type', models.CharField(choices=[('gender', '性別バイアス'), ('age', '年齢バイアス'), ('nationality', '国籍バイアス'), ('education', '学歴バイアス'), ('location', '地域バイアス'), ('name', '名前バイアス'), ('experience', '経験年数バイアス'), ('other', 'その他')], max_length=30, verbose_name='バイアスタイプ')),
                ('severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '重大')], max_length=20, verbose_name='重要度')),
                ('status', models.CharField(choices=[('pending', '未対応'), ('reviewing', '確認中'), ('addressed', '対応済み'), ('dismissed', '却下'), ('false_positive', '誤検知')], default='pending', max_length=20, verbose_name='ステータス')),
                ('target_type', models.CharField(max_length=100, verbose_name='対象タイプ')),
                ('target_id', models.CharField(blank=True, max_length=100, verbose_name='対象ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(verbose_name='説明')),
                ('evidence', models.JSONField(default=dict, verbose_name='証拠データ')),
                ('detection_method', models.CharField(blank=True, max_length=100, verbose_name='検出方法')),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='0-100の範囲', max_digits=5, verbose_name='信頼度スコア')),
                ('ai_analysis', models.TextField(blank=True, verbose_name='AI分析')),
                ('suggested_actions', models.TextField(blank=True, verbose_name='推奨アクション')),
                ('review_notes', models.TextField(blank=True, verbose_name='レビューメモ')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='レビュー日時')),
                ('action_taken', models.TextField(blank=True, verbose_name='実施した対応')),
                ('action_taken_at', models.DateTimeField(blank=True, null=True, verbose_name='対応日時')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='メタデータ')),
                ('is_automated_detection', models.BooleanField(default=True, verbose_name='自動検出')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'バイアスレポート',
                'verbose_name_plural': 'バイアスレポート',
                'db_table': 'bias_reports',
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('gdpr', 'GDPR'), ('equal_opportunity', '機会均等'), ('data_retention', 'データ保持'), ('consent', '同意'), ('transparency', '透明性'), ('bias_detection', 'バイアス検出'), ('privacy', 'プライバシー')], max_length=30, verbose_name='チェックタイプ')),
                ('status', models.CharField(choices=[('pending', '未実施'), ('in_progress', '実施中'), ('passed', '合格'), ('failed', '不合格'), ('warning', '警告')], default='pending', max_length=20, verbose_name='ステータス')),
                ('target_type', models.CharField(max_length=100, verbose_name='対象タイプ')),
                ('target_id', models.CharField(blank=True, max_length=100, verbose_name='対象ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('result_summary', models.TextField(verbose_name='結果サマリー')),
                ('findings', models.JSONField(default=list, verbose_name='発見事項')),
                ('recommendations', models.TextField(blank=True, verbose_name='推奨事項')),
                ('compliance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='コンプライアンススコア')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='チェック日時')),
                ('corrective_actions', models.TextField(blank=True, verbose_name='是正措置')),
                ('corrective_actions_completed', models.BooleanField(default=False, verbose_name='是正完了')),
                ('corrective_actions_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='是正完了日時')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='メタデータ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'コンプライアンスチェック',
                'verbose_name_plural': 'コンプライアンスチェック',
                'db_table': 'compliance_checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('view', '閲覧'), ('export', 'エクスポート'), ('download', 'ダウンロード'), ('print', '印刷'), ('share', '共有')], max_length=20, verbose_name='アクセスタイプ')),
                ('accessed_fields', models.JSONField(default=list, verbose_name='アクセスフィールド')),
                ('purpose', models.TextField(blank=True, verbose_name='アクセス目的')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス')),
                ('user_agent', models.TextField(blank=True, verbose_name='ユーザーエージェント')),
                ('is_authorized', models.BooleanField(default=True, verbose_name='認可済み')),
                ('authorization_reason', models.TextField(blank=True, verbose_name='認可理由')),
                ('is_gdpr_compliant', models.BooleanField(default=True, verbose_name='GDPR準拠')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='メタデータ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='アクセス日時')),
            ],
            options={
                'verbose_name': '個人情報アクセスログ',
                'verbose_name_plural': '個人情報アクセスログ',
                'db_table': 'data_access_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('api_call', 'API呼び出し'), ('agent_session', 'エージェントセッション'), ('matching', 'マッチング'), ('application', '応募'), ('user_action', 'ユーザーアクション'), ('error', 'エラー'), ('performance', 'パフォーマンス')], max_length=30, verbose_name='メトリクスタイプ')),
                ('metric_name', models.CharField(max_length=100, verbose_name='メトリクス名')),
                ('metric_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='メトリクス値')),
                ('metric_unit', models.CharField(blank=True, max_length=50, verbose_name='単位')),
                ('dimensions', models.JSONField(blank=True, default=dict, verbose_name='ディメンション')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='タイムスタンプ')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='メタデータ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'システムメトリクス',
                'verbose_name_plural': 'システムメトリクス',
                'db_table': 'system_metrics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, max_length=254, verbose_name='ユーザーメール')),
                ('user_role', models.CharField(blank=True, max_length=50, verbose_name='ユーザー役割')),
                ('action_type', models.CharField(choices=[('create', '作成'), ('read', '閲覧'), ('update', '更新'), ('delete', '削除'), ('login', 'ログイン'), ('logout', 'ログアウト'), ('export', 'エクスポート'), ('import', 'インポート'), ('approve', '承認'), ('reject', '却下'), ('send', '送信'), ('download', 'ダウンロード')], max_length=20, verbose_name='アクションタイプ')),
                ('resource_type', models.CharField(max_length=100, verbose_name='リソースタイプ')),
                ('resource_id', models.CharField(blank=True, max_length=100, verbose_name='リソースID')),
                ('description', models.TextField(verbose_name='説明')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='変更内容')),
                ('old_values', models.JSONField(blank=True, default=dict, verbose_name='変更前の値')),
                ('new_values', models.JSONField(blank=True, default=dict, verbose_name='変更後の値')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス')),
                ('user_agent', models.TextField(blank=True, verbose_name='ユーザーエージェント')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='リクエストメソッド')),
                ('request_path', models.CharField(blank=True, max_length=500, verbose_name='リクエストパス')),
                ('request_params', models.JSONField(blank=True, default=dict, verbose_name='リクエストパラメータ')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='ステータスコード')),
                ('response_time_ms', models.IntegerField(default=0, verbose_name='レスポンス時間（ミリ秒）')),
                ('severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '重大')], default='low', max_length=20, verbose_name='重要度')),
                ('is_suspicious', models.BooleanField(default=False, verbose_name='不審なアクティビティ')),
                ('is_success', models.BooleanField(default=True, verbose_name='成功')),
                ('error_message', models.TextField(blank=True, verbose_name='エラーメッセージ')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='メタデータ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日時')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '監査ログ',
                'verbose_name_plural': '監査ログ',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
