# Generated by Django 5.2.7 on 2025-10-18 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0002_initial'),
        ('candidates', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='biasreport',
            name='related_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bias_reports', to='candidates.application', verbose_name='関連応募'),
        ),
        migrations.AddField(
            model_name='biasreport',
            name='related_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bias_reports', to='candidates.candidate', verbose_name='関連候補者'),
        ),
        migrations.AddField(
            model_name='biasreport',
            name='related_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bias_reports', to='jobs.job', verbose_name='関連求人'),
        ),
        migrations.AddField(
            model_name='biasreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_bias_reports', to=settings.AUTH_USER_MODEL, verbose_name='レビュー担当者'),
        ),
        migrations.AddField(
            model_name='compliancecheck',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_checks', to=settings.AUTH_USER_MODEL, verbose_name='チェック実施者'),
        ),
        migrations.AddField(
            model_name='compliancecheck',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='dataaccesslog',
            name='target_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_access_logs', to='candidates.candidate', verbose_name='対象候補者'),
        ),
        migrations.AddField(
            model_name='dataaccesslog',
            name='target_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessed_data_logs', to=settings.AUTH_USER_MODEL, verbose_name='対象ユーザー'),
        ),
        migrations.AddField(
            model_name='dataaccesslog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_access_logs', to=settings.AUTH_USER_MODEL, verbose_name='アクセスユーザー'),
        ),
        migrations.AddField(
            model_name='systemmetrics',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_metrics', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-created_at'], name='audit_logs_user_id_6193b2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type', '-created_at'], name='audit_logs_action__a429dc_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='audit_logs_resourc_bda8a6_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address', '-created_at'], name='audit_logs_ip_addr_190b84_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['is_suspicious', '-created_at'], name='audit_logs_is_susp_739b0c_idx'),
        ),
        migrations.AddIndex(
            model_name='biasreport',
            index=models.Index(fields=['bias_type', '-created_at'], name='bias_report_bias_ty_609d96_idx'),
        ),
        migrations.AddIndex(
            model_name='biasreport',
            index=models.Index(fields=['severity', 'status'], name='bias_report_severit_19d3ad_idx'),
        ),
        migrations.AddIndex(
            model_name='biasreport',
            index=models.Index(fields=['target_type', 'target_id'], name='bias_report_target__6af643_idx'),
        ),
        migrations.AddIndex(
            model_name='biasreport',
            index=models.Index(fields=['-confidence_score'], name='bias_report_confide_270e68_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancecheck',
            index=models.Index(fields=['check_type', 'status'], name='compliance__check_t_11e615_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancecheck',
            index=models.Index(fields=['target_type', 'target_id'], name='compliance__target__4457b9_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancecheck',
            index=models.Index(fields=['-created_at'], name='compliance__created_baeed2_idx'),
        ),
        migrations.AddIndex(
            model_name='dataaccesslog',
            index=models.Index(fields=['user', '-created_at'], name='data_access_user_id_6ad251_idx'),
        ),
        migrations.AddIndex(
            model_name='dataaccesslog',
            index=models.Index(fields=['target_user', '-created_at'], name='data_access_target__f64f9e_idx'),
        ),
        migrations.AddIndex(
            model_name='dataaccesslog',
            index=models.Index(fields=['access_type', '-created_at'], name='data_access_access__07764f_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmetrics',
            index=models.Index(fields=['metric_type', '-timestamp'], name='system_metr_metric__25c056_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmetrics',
            index=models.Index(fields=['metric_name', '-timestamp'], name='system_metr_metric__bf467a_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmetrics',
            index=models.Index(fields=['-timestamp'], name='system_metr_timesta_f576a5_idx'),
        ),
    ]
